version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: blog_development
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/blog_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    restart: unless-stopped

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    depends_on:
      - db
      - redis
      - web
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/blog_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  gem_cache: