default: &default
  adapter: postgresql
  encoding: unicode
  host: db  # Matches the Docker service name
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development